//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hardware()
        {
            this.HardwareForService = new HashSet<HardwareForService>();
        }
    
        public int idHardware { get; set; }
        public string title { get; set; }
        public short idManufacturer { get; set; }
        public byte idTypeOfHardware { get; set; }
        public string description { get; set; }
        public int availableAmount { get; set; }
        public int usedAmount { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual TypeOfHardware TypeOfHardware { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HardwareForService> HardwareForService { get; set; }
    }
}
