//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwareForService
    {
        public int id { get; set; }
        public short idService { get; set; }
        public int idHardware { get; set; }
    
        public virtual Hardware Hardware { get; set; }
        public virtual Service Service { get; set; }
    }
}
