//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLogin
    {
        public short idPostLogin { get; set; }
        public byte idPost { get; set; }
        public string password { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
