//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffOnRequest
    {
        public int id { get; set; }
        public int idRequest { get; set; }
        public short idStaff { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
