//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteEmulation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelecommunicationsСompanyEntities : DbContext
    {
        public TelecommunicationsСompanyEntities()
            : base("name=TelecommunicationsСompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Building> Building { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientPayerCodes> ClientPayerCodes { get; set; }
        public virtual DbSet<PayerCode> PayerCode { get; set; }
        public virtual DbSet<PayerCodeServices> PayerCodeServices { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<TempStatement> TempStatement { get; set; }
        public virtual DbSet<TypeOfService> TypeOfService { get; set; }
    }
}
