//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteEmulation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayerCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayerCode()
        {
            this.ClientPayerCodes = new HashSet<ClientPayerCodes>();
            this.PayerCodeServices = new HashSet<PayerCodeServices>();
        }
    
        public string payerCode1 { get; set; }
        public int idBuilding { get; set; }
        public string apartment { get; set; }
        public decimal balanse { get; set; }
    
        public virtual Building Building { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPayerCodes> ClientPayerCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayerCodeServices> PayerCodeServices { get; set; }
    }
}
